### ISSUE TITLE
FullArchiveFailed error

### ISSUE THREAD

**Issue by EFHDev** [TheTechsTech/node-7z-archive#27]
Alright man, ive been stuck on this for a a week or two now, and i just have to bring this up with someone who hopefully knows what the issue is here. When i use FullArchive, or really anything at all, i get this error.

```
FullArchive failed using `7z`, retrying with `7za`.
Error: spawn C:\Users\armyo\OneDrive\Documents\GitHub\SDK2\MTGA-Backend\node_modules\node-7z-archive\binaries\win32\7za.exe ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:285:19)
    at onErrorNT (node:internal/child_process:483:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {errno: -4058, code: 'ENOENT', syscall: 'spawn C:\Users\armyo\OneDrive\Documents\GitH…dules\node-7z-archive\binaries\win32\7za.exe', path: 'C:\Users\armyo\OneDrive\Documents\GitHub\SDK2\…odules\node-7z-archive\binaries\win32\7za.exe', spawnargs: Array(6), …}
```
I have no clue what this is, what it wants from me, or anything of that sort, I could be stupid, dumb, or just incompitent, but i cannot for the life of me get this to extract properly, despite it working just fine with node.7z (Which i would just use otherwise, but the org owner doesnt want to add extra weight)

Heres the code that im calling 7z with its the template pretty much from your readme.md, nothing is undefined, its just upfurther, see the attached file for the entire .js file. 

```
    const filepath = destPath;
    console.log(destPath)
    fullArchive(`${destPath}`, `./`)
    .progress(function (files) {
      console.log('Some files are extracted: %s', files);
    })
    
    // When all is done
    .then(function () {
      console.log('Extracting done!');
    })
    
    // On error
    .catch(function (err) {
      console.error(err);
    });
```
[update.txt](https://github.com/TheTechsTech/node-7z-archive/files/11121485/update.txt)

Just please if im being extremally stupid or anything feel free to yell at me, but i just need someone to tell me if im being stupid, or if it genuinly is just not working.

**Comment by TheTechsTech** [comment]
What version are you using?
Do you see any errors/issues running `npm install node-7z-archive`, or `npm update`?

The error mean `7z` binary not found, which should happen, show itself, at install time, not later, as in https://github.com/TheTechsTech/node-7z-archive/issues/25

**Comment by EFHDev** [comment]
Fresh install seemed to have fixed it... but its weird cause i tried that first, and few times more, somehow i must of been fucking something up somewhere, thats.. my bad????
