### ISSUE TITLE
Tauri+Svelte app stop rendering when importing lib to any Svelte component

### ISSUE THREAD

**Issue by T3kla** [TheTechsTech/node-7z-archive#34]
Using Tauri + Svelte, when importing `import { fullArchive } from "node-7z-archive";` the app goes black and doesn't want to render anything. Of course, it doesn't spit any errors because frontend.

Using JS instead of TS fixes the red .process function but it still makes everything black.

**Comment by TheTechsTech** [comment]
Not sure what your app is trying to accomplish. But this is totally back-end usage.

**Comment by T3kla** [comment]
It doesn't matter what it is trying to acomplish, the fact is that adding the import in any Svelte component breaks the rendering.

**Comment by TheTechsTech** [comment]
It does matter since you have not provide any example of what you are doing. This is an wrapper around an binary executable put on the host system where it's able to run. 

Does 7z actually run on what you are using it for?

**Comment by T3kla** [comment]
Well if you insist.

![image](https://github.com/TheTechsTech/node-7z-archive/assets/23636548/d1af18e1-4372-4504-ab0f-6c66f433aba3)

![image](https://github.com/TheTechsTech/node-7z-archive/assets/23636548/231563a5-1286-4e68-9200-13dbe810fc28)

As I said, the line `import { fullArchive } from "node-7z-archive";` breaks rendering of the app.
It doesn't matter if the `lang="ts"` is there or not.

**Comment by TheTechsTech** [comment]
Does not seem like you did any `npm install node-7z-archive`, you are getting the correct result. 

This is for back-end access, nothing to do with front-end controlling, like what I see. This need to be installed then accessed. Seems you doing a direct import, that's not going to work.

You using package incorrectly, can't help you with that.

**Comment by T3kla** [comment]
It is installed and I did `npm install node-7z-archive` multiple times, also updating Tauri, Vite and every other module. It does appear in the `node_modules` folder with all its files. Still doesn't work.

**Comment by TheTechsTech** [comment]
From what i see it shouldn't work. 

This package just creates or extract archives, does no rendering/web logic, no interacting with DOM, nothing. You importing but see no script logic for extracting or creating some type of archive. 

Seems you need to see the types of npm packages Swelte can compile and do that first.
