### ISSUE TITLE
listArchive types are broken

### ISSUE THREAD

**Issue by Alfagun74** [TheTechsTech/node-7z-archive#35]
only allows "files" in options

**Comment by TheTechsTech** [comment]
What are the options you think is missing or can't be combined?

Also need your script example of what not working and output of that.

**Comment by Alfagun74** [comment]
for example the raw or recursive parameter. i don't use the library anymore so i cant. just try to use it in typescript if you want to reproduce it.

**Comment by TheTechsTech** [comment]
I don't have that issue. 

You say broken, but without any support for it. So there is nothing to fix or look over. 
Which you would need to do **PR**.

**Comment by Alfagun74** [comment]
Apologies that i seem like an idiot. I just switched to another library and im in too much stress rn to reproduce it. I'm sorry for any inconvenience caused.
